// Generated by scripts/generate_cerr_bridge.py
enum CERRScript {
static let source = ####"""
function tps_cerr_analyze(job, library)
% Adapter-owned planC for voxel-mask analysis. Does not import patient DICOM.
s = jsondecode(fileread(fullfile(job,'source.json')));
v = jsondecode(fileread(fullfile(job,'dose.json')));
r = jsondecode(fileread(fullfile(job,'request.json')));
assert(strcmp(fileHash(fullfile(job,'source.json')),r.sourceHash),'Source changed');
assert(strcmp(fileHash(fullfile(job,'dose.json')),r.doseHash),'Dose changed');
assert(r.schemaVersion==1 && s.syntheticOnly,'Synthetic schema-1 case required');
g=s.ct.grid; n=double(g.dimensions(:)'); sp=double(g.spacing(:)');
assert(isequal(g,s.truth.grid) && isequal(g,v.grid),'Grid mismatch');
assert(isequal(g.direction(:)',[1 0 0 0 1 0 0 0 1]),'Oblique grid unsupported');
assert(strcmp(v.units,'Gy') && strcmp(v.modality,'dose'),'Dose must be Gy');
assert(r.binWidthGy>0 && max(v.values)/r.binWidthGy<=5000,'Too many histogram bins');
addpath(library); addToPath(library);
planC=initializeCERR; ix=planC{end};
planC{ix.CERROptions}=struct('ROISampleRate',1,'DVHBlockSize',50);
% CERR research coordinates [L,-P,-S] in cm; reverse slices for ascending z.
x=(g.origin(1)+(0:n(1)-1)*sp(1))/10;
y=-(g.origin(2)+(0:n(2)-1)*sp(2))/10;
z=-fliplr(g.origin(3)+(0:n(3)-1)*sp(3))/10;
ct=flip(permute(reshape(double(s.ct.values),n),[2 1 3]),3);
labels=flip(permute(reshape(double(s.truth.values),n),[2 1 3]),3);
dose=flip(permute(reshape(double(v.values),n),[2 1 3]),3);
scan=initializeCERR('scan'); scan(1).scanArray=ct; scan(1).scanType='CT';
scan(1).scanUID=['native-' s.id]; scan(1).transM=[];
info=initializeScanInfo;
info(1).grid1Units=sp(2)/10; info.grid2Units=sp(1)/10;
info.sizeOfDimension1=n(2); info.sizeOfDimension2=n(1);
info.xOffset=mean(x); info.yOffset=mean(y); info.CTOffset=0;
info.imageType='CT'; info.sliceThickness=sp(3)/10;
for k=1:n(3), info.zValue=z(k); scan(1).scanInfo(k)=info; end
planC{ix.scan}=scan;
d=initializeCERR('dose');
d(1).doseArray=dose; d(1).doseUnits='GY'; d(1).doseScale=1;
d(1).doseOffset=0; d(1).assocScanUID=scan.scanUID; d(1).doseUID=['dose-' r.id];
d(1).horizontalGridInterval=sp(1)/10; d(1).verticalGridInterval=-sp(2)/10;
d(1).coord1OFFirstPoint=x(1); d(1).coord2OFFirstPoint=y(1);
d(1).sizeOfDimension1=n(1); d(1).sizeOfDimension2=n(2); d(1).sizeOfDimension3=n(3);
d(1).zValues=z; d(1).transM=[]; planC{ix.dose}=d;
[sx,sy,sz]=getScanXYZVals(scan); [dx,dy,dz]=getDoseXYZVals(d);
assert(max(abs(sx-x))<1e-9 && max(abs(sy-y))<1e-9 && max(abs(sz-z))<1e-9,'Scan coordinate conversion failed');
assert(max(abs(dx-x))<1e-9 && max(abs(dy-y))<1e-9 && max(abs(dz-z))<1e-9,'Dose coordinate conversion failed');
back=permute(flip(getScanArray(scan),3),[2 1 3]);
assert(isequal(back(:),double(s.ct.values(:))),'CT voxel round trip failed');
back=permute(flip(getDoseArray(1,planC),3),[2 1 3]);
assert(isequal(back(:),double(v.values(:))),'Dose voxel round trip failed');
% Rasterize supplied voxel masks exactly into row runs; no polygon interpolation.
for k=1:numel(s.structures)
    st=initializeCERR('structures');
    st(1).structureName=s.structures(k).name; st(1).assocScanUID=scan.scanUID;
    st(1).strUID=sprintf('native-label-%d',s.structures(k).id);
    st(1).structureColor=s.structures(k).color(:)'; st(1).rasterized=1;
    runs=cell(n(2)*n(3),1); row=0;
    for iz=1:n(3)
        for iy=1:n(2)
            mask=labels(iy,:,iz)==s.structures(k).id;
            starts=find(diff([false mask false])==1);
            stops=find(diff([false mask false])==-1)-1;
            a=zeros(numel(starts),10);
            for j=1:numel(starts)
                a(j,:)=[z(iz),y(iy),x(starts(j)),x(stops(j)),sp(1)/10,iz,iy,starts(j),stops(j),sp(3)/10];
            end
            row=row+1; runs{row}=a;
        end
    end
    st(1).rasterSegments=vertcat(runs{:});
    planC{ix.structures}(k)=st;
end
records={};
for k=1:numel(s.structures)
    expected=dose(labels==s.structures(k).id);
    if isempty(expected), continue; end
    [samples,volumes,isError]=getDVH(k,1,planC);
    assert(~isError && numel(samples)==numel(expected),'CERR sampling did not preserve voxel count');
    assert(all(isfinite(samples)) && all(samples>=0) && all(isfinite(volumes)) && all(volumes>0),'Invalid CERR samples');
    [bins,hist]=doseHist(samples,volumes,r.binWidthGy);
    sorted=sort(samples); q=max(1,ceil(0.05*numel(samples)));
    rec=struct('id',s.structures(k).id,'name',s.structures(k).name,'sampleCount',numel(samples), ...
        'volumeCC',sum(volumes),'meanGy',sum(samples.*volumes)/sum(volumes),'d95Gy',sorted(q), ...
        'maxSampleDifferenceGy',max(abs(sort(samples(:))-sort(expected(:)))), ...
        'binCentersGy',{num2cell(bins)},'differentialVolumeCC',{num2cell(hist)});
    records{end+1}=rec;
end
evidence=struct('MATLABVersion',version,'libraryRoot',library, ...
    'getDVHSHA256',fileHash(which('getDVH')),'doseHistSHA256',fileHash(which('doseHist')), ...
    'bridgeSHA256',fileHash([mfilename('fullpath') '.m']), ...
    'geometry','LPS mm -> [L,-P,-S] cm; YXZ with reversed slices; axis and voxel round trips verified', ...
    'structures','Exact label-mask row runs, not reconstructed polygons', ...
    'sampling','CERR getDVH, ROISampleRate=1; original CT and dose grid; getDoseAt interpolation retained', ...
    'd95','Nearest-rank ceil(0.05*N) on sorted sampled dose; equal voxel volumes', ...
    'scope','Analysis only; no dose recalculation, calibration certification or clinical release');
out=struct('schemaVersion',1,'requestID',r.id,'requestHash',fileHash(fullfile(job,'request.json')), ...
    'sourceHash',r.sourceHash,'doseHash',r.doseHash,'clinicalReleaseAllowed',false,'records',{records},'evidence',evidence);
save(fullfile(job,'planC.mat'),'planC','r','evidence','-v7.3');
f=fopen(fullfile(job,'report.tmp'),'w'); assert(f>=0,'Cannot write report');
c=onCleanup(@() fclose(f)); fprintf(f,'%s',jsonencode(out)); clear c;
movefile(fullfile(job,'report.tmp'),fullfile(job,'report.json'));
fprintf('PASS: CERR planC round trip and getDVH analysis for %d structures.\n',numel(records));
end
function hash=fileHash(path)
f=fopen(path,'rb'); assert(f>=0,'Missing provenance file'); c=onCleanup(@() fclose(f));
md=java.security.MessageDigest.getInstance('SHA-256');
while ~feof(f), md.update(fread(f,1048576,'*uint8')); end
hash=lower(reshape(dec2hex(typecast(md.digest(),'uint8'),2)',1,[]));
end

"""####
}
