// Generated by scripts/generate_matrad_bridge.py
enum MatRadScript {
static let source = ####"""
function tps_matrad_run(job, library)
% GovernedTPS adapter. Uses the separately installed matRad; no bundled matRad code.
requestPath = fullfile(job,'request.json');
sourcePath = fullfile(job,'source.json');
r = jsondecode(fileread(requestPath));
s = jsondecode(fileread(sourcePath));
assert(strcmp(fileHash(sourcePath),r.sourceHash),'Source snapshot hash mismatch');
assert(r.schemaVersion == 1 && s.syntheticOnly,'Synthetic schema-1 input required');
g = s.ct.grid;
n = double(g.dimensions(:)');
assert(isequal(g.direction(:)',[1 0 0 0 1 0 0 0 1]),'Oblique CT unsupported');
assert(numel(s.ct.values)==prod(n) && numel(s.truth.values)==prod(n),'Voxel count mismatch');
assert(isequal(s.truth.grid,g),'CT / label geometry mismatch');
addpath(library);
cfg = matRad_rc;
cfg.userfolders = {fullfile(job,'userdata')};
set(0,'DefaultFigureVisible','off');

% Native flat XYZ with X-fastest -> MATLAB cube [Y,X,Z]. No rotation or resampling.
ct.cubeDim = n([2 1 3]);
ct.cubeHU = {permute(reshape(double(s.ct.values),n),[2 1 3])};
labels = permute(reshape(double(s.truth.values),n),[2 1 3]);
ct.resolution = struct('x',g.spacing(1),'y',g.spacing(2),'z',g.spacing(3));
ct.x = g.origin(1)+(0:n(1)-1)*g.spacing(1);
ct.y = g.origin(2)+(0:n(2)-1)*g.spacing(2);
ct.z = g.origin(3)+(0:n(3)-1)*g.spacing(3);
ct.numOfCtScen = 1;
p = r.settings;
structures = s.structures;
cst = cell(numel(structures),6);
for k = 1:numel(structures)
    st = structures(k);
    cst{k,1} = k-1;
    cst{k,2} = st.name;
    cst{k,3} = 'OAR';
    cst{k,4} = {find(labels == st.id)};
    cst{k,5} = struct('TissueClass',1,'alphaX',0.1,'betaX',0.05,'Priority',k+1,'Visible',true,'visibleColor',st.color(:)');
    cst{k,6} = {};
    if st.id == p.targetID
        assert(~isempty(cst{k,4}{1}),'Target is empty');
        cst{k,3} = 'TARGET'; cst{k,5}.Priority = 1;
        cst{k,6} = {struct(DoseObjectives.matRad_SquaredDeviation(p.targetPenalty,p.targetGy))};
    else
        for j = 1:numel(p.organs)
            o = p.organs(j);
            if o.id == st.id && o.penalty > 0 && ~isempty(cst{k,4}{1})
                cst{k,6} = {struct(DoseObjectives.matRad_SquaredOverdosing(o.penalty,o.ceilingGy))};
            end
        end
    end
end
% Retain unlabelled voxels as an objective-free scoring region; no contour is invented.
if any(labels(:)==0)
    k = size(cst,1)+1;
    cst(k,:) = {k-1,'Unlabelled scoring voxels','OAR',{find(labels==0)}, ...
        struct('TissueClass',1,'alphaX',0.1,'betaX',0.05,'Priority',k+1,'Visible',false),{}};
end
pln.radiationMode = 'photons'; pln.machine = 'Generic';
pln.bioModel = 'none'; pln.multScen = 'nomScen';
pln.numOfFractions = p.fractions;
pln.propStf.gantryAngles = p.gantryAngles(:)';
pln.propStf.couchAngles = zeros(size(pln.propStf.gantryAngles));
pln.propStf.bixelWidth = p.bixelWidthMM;
pln.propStf.numOfBeams = numel(p.gantryAngles);
pln.propStf.isoCenter = repmat(matRad_getIsoCenter(cst,ct,0),pln.propStf.numOfBeams,1);
pln.propOpt.runDAO = false; pln.propOpt.runSequencing = false;
pln.propOpt.quantityOpt = 'physicalDose';
pln.propDoseCalc.doseGrid = struct('resolution',ct.resolution,'x',ct.x,'y',ct.y,'z',ct.z);
ct = matRad_calcWaterEqD(ct,'photons');
stf = matRad_generateStf(ct,cst,pln);
dij = matRad_calcDoseInfluence(ct,cst,stf,pln);
assert(isequal(dij.doseGrid.x,ct.x) && isequal(dij.doseGrid.y,ct.y) && isequal(dij.doseGrid.z,ct.z),'Dose axes differ from CT');
assert(isequal(dij.doseGrid.dimensions,ct.cubeDim),'Dose dimensions differ from CT');
[resultGUI,optimizer] = matRad_fluenceOptimization(dij,cst,pln);
assert(all(isfinite(resultGUI.w)) && all(resultGUI.w>=0),'Invalid optimized weights');
% matRad divides course objectives by fractions internally and returns fraction dose.
dose = permute(resultGUI.physicalDose,[2 1 3]) * p.fractions;
assert(all(isfinite(dose(:))) && all(dose(:)>=0) && any(dose(:)>0),'Invalid optimized dose');
assert(isequal(size(dose),n),'Output dimensions changed');
evidence = struct;
evidence.matRadVersion = char(matRad_version());
evidence.MATLABVersion = version;
evidence.machine = 'Generic photons (uncommissioned)';
evidence.machineSHA256 = fileHash(which('photons_Generic.mat'));
evidence.HLUTSHA256 = fileHash(fullfile(library,'matRad','hluts','matRad_default.hlut'));
evidence.bridgeSHA256 = fileHash([mfilename('fullpath') '.m']);
evidence.optimizer = class(optimizer);
converged = (isa(optimizer,'matRad_OptimizerFmincon') && resultGUI.info.exitflag > 0) || ...
    (isa(optimizer,'matRad_OptimizerIPOPT') && ismember(resultGUI.info.status,[0 1]));
evidence.optimizerConverged = mat2str(converged);
evidence.optimizerInfo = evalc('disp(resultGUI.info)');
evidence.normalization = 'Physical per-fraction dose multiplied by requested fractions; no peak renormalization';
evidence.geometry = 'Native XYZ X-fastest <-> matRad YXZ; original LPS axes retained; no resampling';
evidence.scope = 'Research fluence optimization; no sequencing, deliverability or biological model';
evidence.calcDoseCodeSHA256 = fileHash(which('matRad_calcDoseInfluence'));
evidence.optimizationCodeSHA256 = fileHash(which('matRad_fluenceOptimization'));
save(fullfile(job,'plan.mat'),'ct','cst','pln','stf','resultGUI','evidence','-v7.3');
assert(converged,'Optimizer did not converge; plan.mat and logs retained, no dose proposal emitted');
out = struct('schemaVersion',1,'requestID',r.id,'requestHash',fileHash(requestPath), ...
    'sourceHash',r.sourceHash,'clinicalReleaseAllowed',false,'doseBasis','physical-course-Gy', ...
    'volume',struct('grid',g,'modality','dose','units','Gy','values',dose(:)'), 'evidence',evidence);
fid = fopen(fullfile(job,'result.tmp'),'w');
assert(fid>=0,'Cannot write result');
closer = onCleanup(@() fclose(fid));
fprintf(fid,'%s',jsonencode(out)); clear closer;
movefile(fullfile(job,'result.tmp'),fullfile(job,'result.json'));
fprintf('GovernedTPS matRad result ready: %s\n',fullfile(job,'result.json'));
end

function hash = fileHash(path)
fid = fopen(path,'rb'); assert(fid>=0,'Cannot open provenance file: %s',path);
closer = onCleanup(@() fclose(fid));
md = java.security.MessageDigest.getInstance('SHA-256');
while ~feof(fid)
    bytes = fread(fid,1048576,'*uint8'); md.update(bytes);
end
hash = lower(reshape(dec2hex(typecast(md.digest(),'uint8'),2)',1,[]));
end

"""####
}
