from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / 'scripts/cerr/tps_cerr_analyze.m').read_text()
(root / 'Sources/GovernedTPS/CERRScript.swift').write_text('// Generated by scripts/generate_cerr_bridge.py\nenum CERRScript {\nstatic let source = ####"""\n' + source + '\n"""####\n}\n')
