from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / 'scripts/matrad/tps_matrad_run.m').read_text()
(root / 'Sources/GovernedTPS/MatRadScript.swift').write_text('// Generated by scripts/generate_matrad_bridge.py\nenum MatRadScript {\nstatic let source = ####"""\n' + source + '\n"""####\n}\n')
